### ISSUE TITLE
Комментарий пользователя 

### ISSUE THREAD

**Issue by BSUIRstudent** [Mihail192/EZFixService#1]
Задумка интересная. Есть замечания по поводу интерфейса. Если картинка сырая и будет редактироваться, то неплохо. 
Интерфейс слишком цветастый. В требованиях написано, что приложение для windows 10, а интерфейс взят под IOS.
Если изменить интерфейс, то получится хороший проект.

**Comment by Mihail192** [comment]
Работа над интерфейсом ещё ведётся, поэтому как раз-таки не выложены все мокапы. По поводу цветастости могу согласится, что по стилю не соотносится. Но комментарий про то, что интерфейс взят с IOS, считаю излишним.
