### ISSUE TITLE
Комментарий к проекту EZFixService

### ISSUE THREAD

**Issue by Eugenito** [Mihail192/EZFixService#2]
Данный проект по моему мнению будет полезен ,так как там все понятно и структурировано. Интерфейс красивый, современный и понятный . Замечаний никаких нет. Единственное что хотелось бы больше мокапов. А так в целом мне все понравилось.

**Comment by Mihail192** [comment]
Спасибо за ваш комментарий! Интерфейс ещё дорабатывается, поэтому все мокапы пока не выложены.
